version: '3.8'

services:
  # GO GATEWAY
  gateway:
    build: 
      context: ..
      dockerfile: deployments/Dockerfile.gateway
    ports:
      - "80:8080"
    networks:
      - empire-net
    volumes:
      - ../logs:/app/logs

  # JAVA SERVICE
  java-engine:
    build:
      context: ../java-app
      dockerfile: ../deployments/Dockerfile.java
    networks:
      - empire-net
    depends_on:
      - db

  # PHP SERVICE
  php-core:
    build:
      context: ../php-app
      dockerfile: ../deployments/Dockerfile.php
    networks:
      - empire-net

  # PYTHON UHI
  python-auditor:
    build:
      context: ../scripts/python-uhi
      dockerfile: ../deployments/Dockerfile.python
    volumes:
      - ../logs:/app/logs:ro
    networks:
      - empire-net

  # DATABASE
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: empire_db
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - empire-net

networks:
  empire-net:
    driver: bridge
